autofs-5.1.6 - Use PKG_CHECK_MODULES to detect the libxml2 library
This patch replaces the use of xml2-config with PKG_CHECK_MODULES
to detect the libxml2 library.

Debian is removing xml2-config and now only supports pkg-config
and its macros.

This patch builds on Andreas Hasenack's initial patch [1] and
addresses feedback from Ian Kent [2].

[1] https://www.spinics.net/lists/autofs/msg02204.html
[2] https://www.spinics.net/lists/autofs/msg02206.html

Signed-off-by: Hugh McMaster <hugh.mcmaster@outlook.com>
Signed-off-by: Ian Kent <raven@themaw.net>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -629,8 +629,6 @@ KRB5_LIBS
 LIBSASL
 HAVE_SASL
 SASL_FLAGS
-XML_LIBS
-XML_FLAGS
 LIBLDAP
 HAVE_LDAP
 LDAP_FLAGS
@@ -647,7 +645,8 @@ NSL_LIBS
 NSL_CFLAGS
 LIBCLOCK_GETTIME
 KRB5_CONFIG
-XML_CONFIG
+XML_LIBS
+XML_CFLAGS
 ENABLE_FEDFS
 sssldir
 HAVE_SSS_AUTOFS
@@ -770,6 +769,8 @@ LIBS
 CPPFLAGS
 TIRPC_CFLAGS
 TIRPC_LIBS
+XML_CFLAGS
+XML_LIBS
 NSL_CFLAGS
 NSL_LIBS
 CPP'
@@ -1430,6 +1431,8 @@ Some influential environment variables:
   TIRPC_CFLAGS
               C compiler flags for TIRPC, overriding pkg-config
   TIRPC_LIBS  linker flags for TIRPC, overriding pkg-config
+  XML_CFLAGS  C compiler flags for XML, overriding pkg-config
+  XML_LIBS    linker flags for XML, overriding pkg-config
   NSL_CFLAGS  C compiler flags for NSL, overriding pkg-config
   NSL_LIBS    linker flags for NSL, overriding pkg-config
   CPP         C preprocessor
@@ -4370,81 +4373,83 @@ fi
 
 
 # LDAP SASL auth needs libxml and Kerberos
-for ac_prog in xml2-config
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
-$as_echo_n "checking for $ac_word... " >&6; }
-if ${ac_cv_path_XML_CONFIG+:} false; then :
-  $as_echo_n "(cached) " >&6
-else
-  case $XML_CONFIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_XML_CONFIG="$XML_CONFIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-    for ac_exec_ext in '' $ac_executable_extensions; do
-  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_XML_CONFIG="$as_dir/$ac_word$ac_exec_ext"
-    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-  done
-IFS=$as_save_IFS
 
-  ;;
-esac
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for XML" >&5
+$as_echo_n "checking for XML... " >&6; }
+
+if test -n "$XML_CFLAGS"; then
+    pkg_cv_XML_CFLAGS="$XML_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libxml-2.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libxml-2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_XML_CFLAGS=`$PKG_CONFIG --cflags "libxml-2.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
 fi
-XML_CONFIG=$ac_cv_path_XML_CONFIG
-if test -n "$XML_CONFIG"; then
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $XML_CONFIG" >&5
-$as_echo "$XML_CONFIG" >&6; }
+ else
+    pkg_failed=untried
+fi
+if test -n "$XML_LIBS"; then
+    pkg_cv_XML_LIBS="$XML_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libxml-2.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libxml-2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_XML_LIBS=`$PKG_CONFIG --libs "libxml-2.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
 else
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-$as_echo "no" >&6; }
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
 fi
 
 
-  test -n "$XML_CONFIG" && break
-done
-test -n "$XML_CONFIG" || XML_CONFIG="no"
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for libxml2" >&5
-$as_echo_n "checking for libxml2... " >&6; }
-if test "$XML_CONFIG" = "no"
-then
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-  HAVE_LIBXML=0
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
 else
-  { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XML_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "libxml-2.0" 2>&1`
+        else
+	        XML_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "libxml-2.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$XML_PKG_ERRORS" >&5
+
+	HAVE_LIBXML=0
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	HAVE_LIBXML=0
+else
+	XML_CFLAGS=$pkg_cv_XML_CFLAGS
+	XML_LIBS=$pkg_cv_XML_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
+
   HAVE_LIBXML=1
-  XML_LIBS=`$XML_CONFIG --libs`
-  XML_FLAGS=`$XML_CONFIG --cflags`
-  XML_VER=`$XML_CONFIG --version`
-  XML_MAJOR=`echo $XML_VER|cut -d\. -f1`
-  if test $XML_MAJOR -le 99
-  then
-    XML_MINOR=`echo $XML_VER|cut -d\. -f2`
-    if test $XML_MINOR -le 99
-    then
-      XML_REV=`echo $XML_VER|cut -d\. -f3`
-      if test $XML_REV -le 99; then
 
 $as_echo "#define LIBXML2_WORKAROUND 1" >>confdefs.h
 
-      fi
-    fi
-  fi
+
 fi
+
 for ac_prog in krb5-config
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
